# company-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: company-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: company
  template:
    metadata:
      labels:
        app: company
    spec:
      containers:
      - name: company
        image: praneet8999/startup-hub-company # Replace with your Docker image
        ports:
        - containerPort: 3002
        env:
        - name: RABBITMQ_URI
          value: "amqp://rabbitmq:5672" # Update RabbitMQ URI
