# auth-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth
  template:
    metadata:
      labels:
        app: auth
    spec:
      containers:
      - name: auth
        image: praneet8999/startup-hub-auth # Replace with your Docker image
        ports:
        - containerPort: 3001
        env:
        # - name: MONGO_URI
        #   value: "mongodb://mongo:27017/mydb" # Update MongoDB URI
        - name: RABBITMQ_URI
          value: "amqp://rabbitmq:5672" # Update RabbitMQ URI
